version: '3.8'

services:
  app:
    image: bmtserver:latest  
    container_name: app-container
    ports:
      - "6969:6969"   
    environment:
      - DB_HOST=db    
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydb
    depends_on:
      - db     
  db:
    image: mysql:8.0  
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3446:3446"  
    volumes:
      - mysql-data:/var/lib/mysql   

volumes:
  mysql-data:  

